version: "3"

networks:
  default:
    name: tools
    driver: bridge

services:
  nexus3:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    volumes:
      - /opt/docker/nexus3/data:/nexus-data
    ports:
      - "8084:8081"
      #- "8083:8083"
    user: root
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: --maxmemory 512m
  registry:
    #image: registry:2.8.2
    image: registry
    container_name: registry
    restart: always
    volumes:
      - /opt/docker/registry/data:/var/lib/registry
      - /opt/docker/registry/config.yml:/etc/docker/registry/config.yml:ro
    ports:
      - "8083:5000"
    depends_on:
      - redis
  dnsmasq:
    container_name: dnsmasq
    hostname: dnsmasq
    image: andyshinn/dnsmasq
    restart: always
    #build:
    #    context: ./nginx
    #    dockerfile: Dockerfile
    ports:
        - "53:53/tcp"
        - "53:53/udp"
    cap_add:
        - NET_ADMIN
    #restart: always
    volumes:
        - ./resolv.dnsmasq:/etc/resolv.dnsmasq
        - ./dnsmasqhosts:/etc/dnsmasqhosts
        - ./dnsmasq.conf:/etc/dnsmasq.conf
  gost:
    container_name: gost
    hostname: gost
    image: ginuerzh/gost
    restart: always
    ports:
        - 17788:17788
    command:
        - -L=:17788
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - /opt/docker/nginx/html:/usr/share/nginx/html
      - /opt/docker/nginx/conf.d:/etc/nginx/conf.d
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/logs:/var/log/nginx
  squid:
      image: ubuntu/squid
      container_name: squid
      ports:
        - "3128:3128"
      restart: always
      user: root
      volumes:
      #  - /opt/docker/squid/cache:/var/spool/squid
      #  - /opt/docker/squid/conf.d:/etc/squid/conf.d
      #  - /opt/docker/squid/squid.conf:/etc/squid/squid.conf:ro
      #  - /opt/docker/squid/logs:/var/log/squid
        - /opt/docker/squid/cache:/var/spool/squid
        - /opt/docker/squid/conf.d:/etc/squid/conf.d
        - /opt/docker/squid/logs:/var/log/squid
        - /opt/docker/squid/squid.conf:/etc/squid/squid.conf:ro
